### ISSUE TITLE
Handle period special character as a property key name

### ISSUE THREAD

**Issue by ccreonopoulos** [kreonjr/omniaural#18]
When setting a property to an object that contains keys with the special "." character, OmniAural recognizes that as a key path and created a new nested property.

i.e.
```
initialState = {
   account: {}
}

// Somewhere in the project
OmniAural.state.account.set({
   "name":"John",
   "id.tax":"12345",
   "id.employee":"555"
})

```
The above will **incorrectly** cause the following structure to be created:

```
{
   account: {
       name: "John",
       id: {
           tax: "12345",
           employee: "555"
       }
   }
}
```

Expected structure:
```
{
   account: {
       name: "John",
       "id.tax": "12345",
       "id.employee": "555"
   }
}
```

**Comment by kreonjr** [comment]
Handled by https://github.com/kreonjr/omniaural/pull/23. Closing
